---

- name: Create Workflow
  awx.awx.tower_workflow_job_template:
    description: "{{ item.description }}"
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(false) }}" ## only supported starting from Ansible 2.9
    extra_vars: "{{ item.extra_vars | to_json | default(omit) }}"
    state: present
    survey_enabled: "{{ item.survey_enabled }}"
    survey: "{{ item.survey | to_json }}"    
    tower_oauthtoken: "{{ user_token.json.token }}"
    tower_host: "{{ tower_server }}"
    tower_verify_ssl: no
  with_items: "{{ tower_workflows }}"

# Create links between workflow node 
- name: loop over nodes in schema to add to workflow templates
  include_tasks: "add_workflows_schemas.yml"
  loop: "{{ tower_workflows }}"
  loop_control:
    loop_var: workflow_loop_var 